# Site Configuration
baseURL = "https://skillicinski.github.io/"
defaultContentLanguage = "en"

enableRobotsTXT = true

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS"]
